// Purpose: Generate explicit audience grids, sample reproducibly, evaluate typed reactions, and aggregate code-owned effects.
import{readFile,writeFile}from'node:fs/promises';import{estimateCostUsd,estimateTokens}from'./jev-client.mjs';export{createFakeProvider,createJevClient}from'./jev-client.mjs';
export function validateDesign(d){if(!d?.axes||typeof d.axes!=='object'||Array.isArray(d.axes)||!Object.keys(d.axes).length)throw new TypeError('design requires axes');for(const[k,v]of Object.entries(d.axes))if(!Array.isArray(v)||!v.length||v.some(x=>typeof x!=='string'||!x))throw new TypeError(`axis ${k} requires non-empty string levels`);if(!Array.isArray(d.objections)||!d.objections.length||d.objections.length>255)throw new TypeError('design requires 1 to 255 declared objections');return d}
export function factorial(axes){return Object.entries(axes).reduce((rows,[key,levels])=>rows.flatMap(row=>levels.map(level=>({...row,[key]:level}))),[{}])}
function rng(seed){let x=(Number(seed)||1)>>>0;return()=>((x=(x*1664525+1013904223)>>>0)/2**32)}
export function chooseRespondents(design,{maxFull=64,budget=200,seed=42}={}){validateDesign(design);const all=factorial(design.axes);if(all.length<=maxFull)return{mode:'full-factorial',respondents:all,totalCombinations:all.length};const random=rng(seed),indices=all.map((_,i)=>i);for(let i=indices.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[indices[i],indices[j]]=[indices[j],indices[i]]}const selected=[],used=new Set;for(const[axis,levels]of Object.entries(design.axes))for(const level of levels){const idx=all.findIndex((r,i)=>!used.has(i)&&r[axis]===level);if(idx>=0&&selected.length<budget){selected.push(all[idx]);used.add(idx)}}for(const i of indices)if(selected.length<budget&&!used.has(i)){selected.push(all[i]);used.add(i)}return{mode:'seeded-balanced-sample',respondents:selected,totalCombinations:all.length,seed}}
export function reactionQuestions(design){return{would_engage:{type:'noul',instructions:'Would this explicitly described respondent engage with the message?'},trust:{type:'score',instructions:'How much would this respondent trust the message?',criteria:['No trust','Low','Moderate','High']},would_convert:{type:'noul',instructions:'Would this respondent take the requested conversion action?'},objection:{type:'choice',instructions:'Which declared objection category best matches this respondent reaction?',criteria:Object.fromEntries(design.objections.map(x=>[x,null]))}}}
export function wilson(successes,n,z=1.96){if(!n)return{low:0,high:0};const p=successes/n,d=1+z*z/n,c=(p+z*z/(2*n))/d,m=z*Math.sqrt((p*(1-p)+z*z/(4*n))/n)/d;return{low:Math.max(0,c-m),high:Math.min(1,c+m)}}
function metrics(a){return{engage:a.would_engage.noul,trust:a.trust.score/Math.max(1,Object.keys(a.trust.legend).length-1),convert:a.would_convert.noul}}
export function mainEffects(rows,axes){const out={};for(const[axis,levels]of Object.entries(axes)){out[axis]={};for(const level of levels){const selected=rows.filter(r=>r.respondent[axis]===level),m=selected.map(r=>metrics(r.answers));out[axis][level]={n:selected.length,engage:m.reduce((s,x)=>s+x.engage,0)/(m.length||1),trust:m.reduce((s,x)=>s+x.trust,0)/(m.length||1),convert:m.reduce((s,x)=>s+x.convert,0)/(m.length||1),convertWilson:wilson(m.reduce((s,x)=>s+(x.convert>=.5?1:0),0),m.length)}}}return out}
async function parallel(items,limit,fn){let i=0;const out=[];await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(i<items.length){const n=i++;out[n]=await fn(items[n])}}));return out}
export async function simulate({design,message,provider,maxFull=64,budget=200,seed=42,concurrency=8,respondents}){validateDesign(design);const selection=respondents?{mode:'provided',respondents,totalCombinations:factorial(design.axes).length}:chooseRespondents(design,{maxFull,budget,seed}),questions=reactionQuestions(design);const rows=await parallel(selection.respondents,concurrency,async respondent=>{const r=await provider({state:{message,respondent},questions});return{respondent,answers:r.answers,usage:r.usage}});const input=rows.reduce((n,r)=>n+r.usage.input_tokens,0);return{...selection,rows,effects:mainEffects(rows,design.axes),usage:{input_tokens:input,estimated_cost_usd:estimateCostUsd(input)}}}
export async function compare({design,messageA,messageB,provider,...options}){const selected=chooseRespondents(design,options).respondents;const a=await simulate({design,message:messageA,provider,respondents:selected,...options});const b=await simulate({design,message:messageB,provider,respondents:selected,...options});return{respondents:selected,a,b}}
export function estimateSimulation(design,message,options={}){const s=chooseRespondents(design,options),per=estimateTokens({state:{message,respondent:s.respondents[0]},questions:reactionQuestions(design)}),n=s.respondents.length;return{mode:s.mode,respondents:n,requests:n,estimatedInputTokens:n*per,estimatedCostUsd:estimateCostUsd(n*per)}}
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');export function renderHtml(report){const rows=report.rows.map(r=>`<tr><td>${esc(Object.entries(r.respondent).map(([k,v])=>`${k}: ${v}`).join(', '))}</td><td>${Math.round(r.answers.would_engage.noul*100)}</td><td>${Math.round(r.answers.would_convert.noul*100)}</td><td>${esc(r.answers.objection.choice)}</td></tr>`).join('');const effects=Object.entries(report.effects).flatMap(([a,l])=>Object.entries(l).map(([v,m])=>`<tr><td>${esc(a)}</td><td>${esc(v)}</td><td>${Math.round(m.engage*100)}</td><td>${Math.round(m.convert*100)}</td></tr>`)).join('');return`<!doctype html><html><head><meta charset="utf-8"><title>Jev CrowdSim</title><style>body{font:16px system-ui;max-width:1100px;margin:50px auto;background:#fbf6ed;color:#1f2937}table{border-collapse:collapse;width:100%;margin:20px 0}td,th{padding:10px;border-bottom:1px solid #d6cfc3;text-align:left}h1{font-size:4rem}</style></head><body><h1>CrowdSim</h1><p>${report.mode}; ${report.rows.length} declared respondents.</p><h2>Main effects</h2><table><tr><th>Axis</th><th>Level</th><th>Engage</th><th>Convert</th></tr>${effects}</table><h2>Every respondent</h2><table><tr><th>Traits</th><th>Engage</th><th>Convert</th><th>Objection</th></tr>${rows}</table></body></html>`}
export async function writeReport(report,path){await writeFile(path,renderHtml(report));return path}export async function loadDesign(path){return validateDesign(JSON.parse(await readFile(path,'utf8')))}
